// Copyright (c) 2014-2017 Coin Sciences Ltd
// TreasureLandCoin code distributed under the GPLv3 license, see COPYING file.

#ifndef TREASURELANDCOINVERSION_H
#define	TREASURELANDCOINVERSION_H

#define TREASURELANDCOIN_VERSION_MAJOR     1
#define TREASURELANDCOIN_VERSION_MINOR     0
#define TREASURELANDCOIN_VERSION_REVISION  0
#define TREASURELANDCOIN_VERSION_STAGE     2
#define TREASURELANDCOIN_VERSION_BUILD     1

#define TREASURELANDCOIN_PROTOCOL_VERSION 10008


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define TREASURELANDCOIN_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define TREASURELANDCOIN_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define TREASURELANDCOIN_BUILD_DESC "1.0 beta 1"
#define TREASURELANDCOIN_BUILD_DESC_NUMERIC 10000201

#ifndef TREASURELANDCOIN_BUILD_DESC
#ifdef BUILD_SUFFIX
#define TREASURELANDCOIN_BUILD_DESC TREASURELANDCOIN_BUILD_DESC_WITH_SUFFIX(TREASURELANDCOIN_VERSION_MAJOR, TREASURELANDCOIN_VERSION_MINOR, TREASURELANDCOIN_VERSION_REVISION, TREASURELANDCOIN_VERSION_BUILD, BUILD_SUFFIX)
#else
#define TREASURELANDCOIN_BUILD_DESC TREASURELANDCOIN_BUILD_DESC_FROM_UNKNOWN(TREASURELANDCOIN_VERSION_MAJOR, TREASURELANDCOIN_VERSION_MINOR, TREASURELANDCOIN_VERSION_REVISION, TREASURELANDCOIN_VERSION_BUILD)
#endif
#endif

#define TREASURELANDCOIN_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef TREASURELANDCOIN_FULL_VERSION
#define TREASURELANDCOIN_FULL_VERSION TREASURELANDCOIN_FULL_DESC(TREASURELANDCOIN_BUILD_DESC, TREASURELANDCOIN_PROTOCOL_VERSION)
#endif


#endif	/* TREASURELANDCOINVERSION_H */

